# Generated by Django 5.2.15 on 2026-06-22 08:00

import django.db.models.deletion
from django.db import migrations, models


def migrate_department_to_service(apps, schema_editor):
    User = apps.get_model("users", "User")
    Service = apps.get_model("users", "Service")

    dept_map = {}
    for user in User.objects.exclude(department=""):
        dept = user.department.strip()
        if not dept:
            continue
        if dept not in dept_map:
            service, _ = Service.objects.get_or_create(name=dept)
            dept_map[dept] = service
        user.service = dept_map[dept]
        user.save(update_fields=["service"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_site_user_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.service'),
        ),
        migrations.RunPython(migrate_department_to_service, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
