# Generated by Django 5.2.15 on 2026-06-22 09:39

import apps.users.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agence_interim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='cadre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='coefficient',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='commentaire_rh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='forfait_jour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='salaire_brut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('non_binaire', 'Non-Binaire')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('sortie', 'Sortie')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, validators=[apps.users.validators.validate_phone]),
        ),
        migrations.AddField(
            model_name='user',
            name='tickets_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Intérim'), ('alternance', 'Alternance'), ('stage', 'Stage')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.fonction'),
        ),
    ]
