# Generated by Django 5.2.15 on 2026-06-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fonction_user_agence_interim_user_cadre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commentaire_rh',
        ),
        migrations.DeleteModel(
            name='Fonction',
        ),
    ]
