# Generated by Django 5.2.15 on 2026-06-22 09:53

from django.db import migrations, models


def fill_empty_matricules(apps, schema_editor):
    User = apps.get_model("users", "User")
    qs = User.objects.filter(matricule="")
    if not qs.exists():
        return
    import re
    existing = User.objects.exclude(matricule="").values_list("matricule", flat=True)
    used = {m for m in existing if re.match(r"^\d+$", m)}
    next_num = 1
    if used:
        next_num = max(int(m) for m in used) + 1
    for user in qs.iterator():
        while f"{next_num:08d}" in used:
            next_num += 1
        user.matricule = f"{next_num:08d}"
        used.add(user.matricule)
        user.save(update_fields=["matricule"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_fonction_commentaire'),
    ]

    operations = [
        migrations.RunPython(fill_empty_matricules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
