# Generated by Django 5.2.15 on 2026-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_unique_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rh', 'RH'), ('manager', 'Manager'), ('employee', 'Employé'), ('stagiaire', 'Stagiaire'), ('alternant', 'Alternant')], default='employee', max_length=20),
        ),
    ]
