# Generated by Django 5.2.15 on 2026-06-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.TextField(blank=True, default=''),
        ),
    ]
