# Generated by Django 5.2.15 on 2026-06-22 11:30

import django.db.models.deletion
from django.db import migrations, models


ANNUAL_TEMPLATE = {
    "sections": [
        {
            "id": "bilan",
            "title": "Bilan de l'année écoulée",
            "questions": [
                {"id": "realisations", "label": "Principales réalisations", "type": "textarea", "answer": ""},
                {"id": "difficultes", "label": "Difficultés rencontrées", "type": "textarea", "answer": ""},
                {"id": "satisfaction", "label": "Niveau de satisfaction général", "type": "rating", "answer": None},
            ],
        },
        {
            "id": "competences",
            "title": "Compétences et savoir-être",
            "questions": [
                {"id": "points_forts", "label": "Points forts", "type": "textarea", "answer": ""},
                {"id": "axes_amelioration", "label": "Axes d'amélioration", "type": "textarea", "answer": ""},
                {"id": "competences_techniques", "label": "Compétences techniques à développer", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "objectifs",
            "title": "Objectifs pour l'année à venir",
            "questions": [
                {"id": "objectifs_metier", "label": "Objectifs métier", "type": "textarea", "answer": ""},
                {"id": "objectifs_personnels", "label": "Objectifs de développement personnel", "type": "textarea", "answer": ""},
                {"id": "indicateurs", "label": "Indicateurs de réussite", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "formation",
            "title": "Formation et évolution",
            "questions": [
                {"id": "souhaits_formation", "label": "Souhaits de formation", "type": "textarea", "answer": ""},
                {"id": "souhaits_mobilite", "label": "Souhaits de mobilité", "type": "textarea", "answer": ""},
                {"id": "evolution_souhaitee", "label": "Perspectives d'évolution souhaitées", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "commentaires",
            "title": "Commentaires",
            "questions": [
                {"id": "commentaire_employe", "label": "Commentaire de l'employé", "type": "textarea", "answer": ""},
                {"id": "commentaire_manager", "label": "Commentaire du manager", "type": "textarea", "answer": ""},
            ],
        },
    ],
}

PROFESSIONAL_TEMPLATE = {
    "sections": [
        {
            "id": "parcours",
            "title": "Parcours professionnel",
            "questions": [
                {"id": "poste_actuel", "label": "Poste actuel et missions", "type": "textarea", "answer": ""},
                {"id": "parcours_anterieur", "label": "Parcours depuis le dernier entretien", "type": "textarea", "answer": ""},
                {"id": "competences_acquises", "label": "Compétences acquises", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "formation",
            "title": "Actions de formation",
            "questions": [
                {"id": "formations_suivies", "label": "Formations suivies", "type": "textarea", "answer": ""},
                {"id": "formations_souhaitees", "label": "Formations souhaitées", "type": "textarea", "answer": ""},
                {"id": "cpf", "label": "Utilisation du CPF", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "projet",
            "title": "Projet professionnel",
            "questions": [
                {"id": "souhaits_evolution", "label": "Souhaits d'évolution", "type": "textarea", "answer": ""},
                {"id": "mobilite", "label": "Mobilité géographique / fonctionnelle", "type": "textarea", "answer": ""},
                {"id": "vae", "label": "Validation des Acquis (VAE)", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "bilan",
            "title": "Bilan et perspectives",
            "questions": [
                {"id": "bilan_general", "label": "Bilan général de la période", "type": "textarea", "answer": ""},
                {"id": "perspectives", "label": "Perspectives et objectifs", "type": "textarea", "answer": ""},
                {"id": "conditions", "label": "Conditions de travail", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "commentaires",
            "title": "Commentaires",
            "questions": [
                {"id": "commentaire_employe", "label": "Commentaire de l'employé", "type": "textarea", "answer": ""},
                {"id": "commentaire_manager", "label": "Commentaire du manager", "type": "textarea", "answer": ""},
            ],
        },
    ],
}


def seed_default_templates(apps, schema_editor):
    InterviewTemplate = apps.get_model("interviews", "InterviewTemplate")
    if not InterviewTemplate.objects.filter(type="annual").exists():
        InterviewTemplate.objects.create(
            name="Entretien annuel",
            type="annual",
            description="Template par défaut pour l'entretien annuel d'évaluation",
            sections=ANNUAL_TEMPLATE["sections"],
        )
    if not InterviewTemplate.objects.filter(type="professional").exists():
        InterviewTemplate.objects.create(
            name="Entretien professionnel",
            type="professional",
            description="Template par défaut pour l'entretien professionnel",
            sections=PROFESSIONAL_TEMPLATE["sections"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('annual', 'Entretien annuel'), ('professional', 'Entretien professionnel')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.interviewtemplate'),
        ),
        migrations.RunPython(seed_default_templates, migrations.RunPython.noop),
    ]
