# Generated by Django 5.2.15 on 2026-06-22 12:00

from django.db import migrations, models


BILAN_TEMPLATE = {
    "sections": [
        {
            "id": "bilan_periode",
            "title": "Bilan de la période",
            "questions": [
                {"id": "realisations", "label": "Réalisations marquantes", "type": "textarea", "answer": ""},
                {"id": "difficultes", "label": "Difficultés rencontrées", "type": "textarea", "answer": ""},
                {"id": "satisfaction", "label": "Niveau de satisfaction", "type": "rating", "answer": None},
            ],
        },
        {
            "id": "objectifs",
            "title": "Objectifs",
            "questions": [
                {"id": "objectifs_atteints", "label": "Objectifs atteints", "type": "textarea", "answer": ""},
                {"id": "objectifs_futurs", "label": "Objectifs à venir", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "commentaires",
            "title": "Commentaires",
            "questions": [
                {"id": "commentaire_employe", "label": "Commentaire de l'employé", "type": "textarea", "answer": ""},
                {"id": "commentaire_manager", "label": "Commentaire du manager", "type": "textarea", "answer": ""},
            ],
        },
    ],
}

FORFAIT_TEMPLATE = {
    "sections": [
        {
            "id": "charge_travail",
            "title": "Charge de travail",
            "questions": [
                {"id": "volume_travail", "label": "Volume de travail et répartition", "type": "textarea", "answer": ""},
                {"id": "organisation", "label": "Organisation du temps de travail", "type": "textarea", "answer": ""},
                {"id": "amplitude", "label": "Amplitude des journées", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "equilibre",
            "title": "Équilibre vie pro/perso",
            "questions": [
                {"id": "charge_satisfaisante", "label": "La charge est-elle satisfaisante ?", "type": "rating", "answer": None},
                {"id": "conges_pris", "label": "Congés pris sur la période", "type": "textarea", "answer": ""},
                {"id": "droit_deconnexion", "label": "Respect du droit à la déconnexion", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "commentaires",
            "title": "Commentaires",
            "questions": [
                {"id": "commentaire_employe", "label": "Commentaire de l'employé", "type": "textarea", "answer": ""},
                {"id": "commentaire_manager", "label": "Commentaire du manager", "type": "textarea", "answer": ""},
            ],
        },
    ],
}

FIN_CARRIERE_TEMPLATE = {
    "sections": [
        {
            "id": "parcours",
            "title": "Parcours et bilan de carrière",
            "questions": [
                {"id": "parcours_global", "label": "Parcours global dans l'entreprise", "type": "textarea", "answer": ""},
                {"id": "contributions", "label": "Contributions et réalisations", "type": "textarea", "answer": ""},
                {"id": "competences_acquises", "label": "Compétences acquises", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "projet_fin_carriere",
            "title": "Projet de fin de carrière",
            "questions": [
                {"id": "souhaits_fin_carriere", "label": "Souhaits pour la fin de carrière", "type": "textarea", "answer": ""},
                {"id": "amenagements", "label": "Aménagements souhaités", "type": "textarea", "answer": ""},
                {"id": "transmission", "label": "Transmission des savoirs", "type": "textarea", "answer": ""},
            ],
        },
        {
            "id": "preparation_depart",
            "title": "Préparation au départ",
            "questions": [
                {"id": "date_prevue", "label": "Date de départ envisagée", "type": "textarea", "answer": ""},
                {"id": "formalites", "label": "Formalités et accompagnement", "type": "textarea", "answer": ""},
                {"id": "commentaire_employe", "label": "Commentaire de l'employé", "type": "textarea", "answer": ""},
            ],
        },
    ],
}


def seed_new_templates(apps, schema_editor):
    InterviewTemplate = apps.get_model("interviews", "InterviewTemplate")
    defaults = [
        ("Entretien de bilan", "bilan", BILAN_TEMPLATE["sections"]),
        ("Entretien forfait jours et charges", "forfait", FORFAIT_TEMPLATE["sections"]),
        ("Entretien de fin de carrière", "fin_carriere", FIN_CARRIERE_TEMPLATE["sections"]),
    ]
    for name, type_key, sections in defaults:
        if not InterviewTemplate.objects.filter(type=type_key).exists():
            InterviewTemplate.objects.create(name=name, type=type_key, sections=sections)


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.CharField(choices=[('annual', 'Entretien annuel'), ('professional', 'Entretien professionnel'), ('bilan', 'Entretien de bilan'), ('forfait', 'Entretien forfait jours et charges'), ('fin_carriere', 'Entretien de fin de carrière')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='type',
            field=models.CharField(choices=[('annual', 'Entretien annuel'), ('professional', 'Entretien professionnel'), ('bilan', 'Entretien de bilan'), ('forfait', 'Entretien forfait jours et charges'), ('fin_carriere', 'Entretien de fin de carrière')], max_length=20),
        ),
        migrations.RunPython(seed_new_templates, migrations.RunPython.noop),
    ]
