# Generated by Django 5.2.15 on 2026-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('signed', 'Signé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
    ]
