# Generated by Django 5.2.15 on 2026-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_add_signed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='interview_docs/'),
        ),
    ]
