# Generated by Django 5.2.15 on 2026-06-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interview_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.CharField(choices=[('annual', "Entretien d'évaluation"), ('professional', 'Entretien professionnel'), ('bilan', 'Entretien de bilan'), ('forfait', 'Entretien forfait jours et charges'), ('fin_carriere', 'Entretien de fin de carrière')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='type',
            field=models.CharField(choices=[('annual', "Entretien d'évaluation"), ('professional', 'Entretien professionnel'), ('bilan', 'Entretien de bilan'), ('forfait', 'Entretien forfait jours et charges'), ('fin_carriere', 'Entretien de fin de carrière')], max_length=20),
        ),
    ]
